name: Java Test with MAven

on: 
  pull_request:
    branches: ["main"]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        chache: maven
    - name: Test with Maven
      run: mvn -B test --file pom.xml
